#!/usr/bin/python2.7

import RPi.GPIO as GPIO
import sys, os, re, time, fcntl

fd = sys.stdin.fileno()
fl = fcntl.fcntl(fd, fcntl.F_GETFL)
fcntl.fcntl(fd, fcntl.F_SETFL, fl | os.O_NONBLOCK)

GPIO.setmode(GPIO.BOARD)
pin = 11
GPIO.setup(pin, GPIO.OUT)

dtr = re.compile('.*TIOCM_DTR.*')
isDone = re.compile('^$')
start = time.time()

def reset():
  GPIO.output(pin, GPIO.HIGH)
  time.sleep(0.12)
  GPIO.output(pin, GPIO.LOW)
  print "Leaving reset()"

def process():
  while True:
    try: 
      duration = time.time() - start
      input = sys.stdin.readline().strip()
      # Debugging the strace pipe
      #print "text: ["+input+"]"
      if duration > 60:
        print "autoreset: Timeout reached, exiting!"
        return
      if isDone.match(input):
        return
      if dtr.match(input):
        print "Calling reset()!"
        reset()
        print "Done toggling pin."
    except  IOError:
    #  print "Exception!"
    #  break
      continue
    #  pass

process()

print "Cleaning up gpio."

GPIO.cleanup()

print "autoreset: done!"
sys.exit(0)
